<Project>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <Version>1.0.1-libvlc-test.1</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
