<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>HazzKaraokeHoster.Playback</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\HazzKaraokeHoster.Core\HazzKaraokeHoster.Core.csproj" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>
</Project>
